environment: development
debug: true
log_level: DEBUG

# Database
database:
  host: localhost
  port: 5432
  name: minca
  user: minca
  password: minca
  pool_size: 5
  max_overflow: 10

# Redis (for dev, using Redis instead of SQS)
redis:
  host: localhost
  port: 6379
  db: 0
  password: null
  max_connections: 10

# Storage (using MinIO for local S3 compatibility)
storage:
  provider: minio
  endpoint: http://localhost:9000
  access_key: minio
  secret_key: minio12345
  bucket_raw: raw
  bucket_exports: exports
  region: us-east-1

# Message Queues (Local in-memory for dev, SQS for production)
queue_backend: local  # local | sqs
queues:
  extractor: "mvp-underwriting-extractor"
  codifier: "mvp-underwriting-codifier"
  transform: "mvp-underwriting-transform"
  exporter: "mvp-underwriting-exporter"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
  jwt_secret: "dev-secret-key-change-in-production"

# ML Configuration
ml:
  models:
    embedding: "intfloat/multilingual-e5-large"
    reranker: "cross-encoder/ms-marco-MiniLM-L-2-v2"
  
  thresholds:
    auto_accept: 0.85
    review_required: 0.70
    
  batch_sizes:
    codification: 50
    extraction: 100

# Feature Flags
features:
  enable_auto_codify: true
  enable_batch_processing: true
  enable_audit_logging: true
  enable_file_validation: true
  enable_real_time_updates: true

# File Processing
file_processing:
  max_file_size: 52428800  # 50MB
  allowed_extensions:
    - .xlsx
    - .xls
    - .csv
    - .pdf
    - .eml
  
  extraction_timeout: 300  # 5 minutes
  processing_timeout: 600  # 10 minutes

# Monitoring
monitoring:
  enable_metrics: true
  metrics_port: 9090
  enable_tracing: false
  
# Development specific
dev:
  auto_reload: true
  mock_external_services: true
  seed_data: true
  enable_debug_routes: true