[tool.poetry]
name = "storage"
version = "0.1.0"
description = "S3 storage utilities"
authors = ["Minca AI Team <team@mincaai.com>"]
packages = [{ include = "app", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.34.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
black = "^24.0"
ruff = "^0.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"