services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    container_name: minca_api
    env_file:
      - configs/env/.env.development
      - configs/env/service-specific/.env.api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      S3_BUCKET_RAW: ${S3_BUCKET_RAW}
      S3_BUCKET_EXPORTS: ${S3_BUCKET_EXPORTS}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      QUEUE_BACKEND: ${QUEUE_BACKEND:-local}
    ports: ["8000:8000"]
    volumes:
      - ./services/api/src:/app/services/api/src  # hot reload-friendly

  document-processor:
    build:
      context: .
      dockerfile: services/document-processor/Dockerfile
    container_name: minca_document_processor
    env_file:
      - configs/env/.env.development
      - configs/env/service-specific/.env.document-processor
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      S3_BUCKET_RAW: ${S3_BUCKET_RAW}
      S3_BUCKET_EXPORTS: ${S3_BUCKET_EXPORTS}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      QUEUE_BACKEND: ${QUEUE_BACKEND:-local}
    ports: ["8001:8001"]
    volumes:
      - ./services/document-processor/src:/app/services/document-processor/src  # hot reload

  vehicle-codifier:
    build:
      context: .
      dockerfile: services/vehicle-codifier/Dockerfile
    container_name: minca_vehicle_codifier
    env_file:
      - configs/env/.env.development
      - configs/env/service-specific/.env.vehicle-codifier
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    ports: ["8002:8002"]
    volumes:
      - ./services/vehicle-codifier/src:/app/src  # hot reload

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: minca_ui
    env_file:
      - configs/env/service-specific/.env.ui
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_DOCUMENT_PROCESSOR_URL: http://localhost:8001
    ports: ["3000:3000"]
    depends_on: [api, document-processor]
    volumes:
      - ./ui/src:/app/src  # hot reload for development

  smart-intake:
    build:
      context: .
      dockerfile: services/smart-intake-service/Dockerfile
    container_name: minca_smart_intake
    env_file:
      - configs/env/service-specific/.env.smart-intake
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      S3_BUCKET_RAW: ${S3_BUCKET_RAW}
      S3_BUCKET_EXPORTS: ${S3_BUCKET_EXPORTS}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      # Add Azure Graph credentials in env file:
      # AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET
    ports: ["8003:8003"]
    volumes:
      - ./services/smart-intake-service/app:/app/services/smart-intake-service/app  # hot reload
