"""add email_message and email_attachment tables

Revision ID: 001
Revises: 
Create Date: 2025-01-12 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_message_from_email'), 'email_message', ['from_email'], unique=False)
    
    op.create_table('email_attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_message_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('s3_uri', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_attachment_email_message_id'), 'email_attachment', ['email_message_id'], unique=False)
    op.create_index('ix_email_attachment_sha256', 'email_attachment', ['sha256'], unique=False)
    
    # Add email_message_id column to case table
    op.add_column('case', sa.Column('email_message_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_case_email_message_id'), 'case', ['email_message_id'], unique=False)
    op.create_foreign_key(None, 'case', 'email_message', ['email_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case', type_='foreignkey')
    op.drop_index(op.f('ix_case_email_message_id'), table_name='case')
    op.drop_column('case', 'email_message_id')
    
    op.drop_index('ix_email_attachment_sha256', table_name='email_attachment')
    op.drop_index(op.f('ix_email_attachment_email_message_id'), table_name='email_attachment')
    op.drop_table('email_attachment')
    
    op.drop_index(op.f('ix_email_message_from_email'), table_name='email_message')
    op.drop_table('email_message')
    # ### end Alembic commands ###