"""Create catver_record table for CATVER_ENVIOS.xlsx data

Revision ID: b18d56f08e82
Revises: 002
Create Date: 2025-09-15 23:35:09.149622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = 'b18d56f08e82'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catver_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marca', sa.String(length=25), nullable=False),
    sa.Column('submarca', sa.String(length=52), nullable=False),
    sa.Column('numver', sa.Integer(), nullable=False),
    sa.Column('ramo', sa.Integer(), nullable=False),
    sa.Column('cvemarc', sa.Integer(), nullable=False),
    sa.Column('cvesubm', sa.Integer(), nullable=False),
    sa.Column('martip', sa.Integer(), nullable=False),
    sa.Column('cvesegm', sa.String(length=51), nullable=False),
    sa.Column('modelo', sa.Integer(), nullable=False),
    sa.Column('cvegs', sa.Integer(), nullable=False),
    sa.Column('descveh', sa.String(length=150), nullable=False),
    sa.Column('idperdiod', sa.Integer(), nullable=False),
    sa.Column('sumabas', sa.Float(), nullable=False),
    sa.Column('tipveh', sa.String(length=19), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catver_brand_model_year', 'catver_record', ['marca', 'submarca', 'modelo'], unique=False)
    op.create_index('ix_catver_description', 'catver_record', ['descveh'], unique=False)
    op.create_index(op.f('ix_catver_record_cvegs'), 'catver_record', ['cvegs'], unique=True)
    op.create_index(op.f('ix_catver_record_marca'), 'catver_record', ['marca'], unique=False)
    op.create_index(op.f('ix_catver_record_modelo'), 'catver_record', ['modelo'], unique=False)
    op.create_index(op.f('ix_catver_record_submarca'), 'catver_record', ['submarca'], unique=False)
    op.create_index(op.f('ix_correction_row_idx'), 'correction', ['row_idx'], unique=False)
    op.create_index(op.f('ix_correction_run_id'), 'correction', ['run_id'], unique=False)
    op.alter_column('email_attachment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('email_message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('email_attachment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_correction_run_id'), table_name='correction')
    op.drop_index(op.f('ix_correction_row_idx'), table_name='correction')
    op.drop_index(op.f('ix_catver_record_submarca'), table_name='catver_record')
    op.drop_index(op.f('ix_catver_record_modelo'), table_name='catver_record')
    op.drop_index(op.f('ix_catver_record_marca'), table_name='catver_record')
    op.drop_index(op.f('ix_catver_record_cvegs'), table_name='catver_record')
    op.drop_index('ix_catver_description', table_name='catver_record')
    op.drop_index('ix_catver_brand_model_year', table_name='catver_record')
    op.drop_table('catver_record')
    # ### end Alembic commands ###