[tool.poetry]
name = "common"
version = "0.1.0"
packages = [{ include = "app", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.8.0"
pydantic-settings = "^2.0.3"
PyYAML = "^6.0.1"
python-dateutil = "^2.8.2"
pytz = "^2023.3"
rich = "^13.5.0"

[tool.poetry.group.dev.dependencies]
black = "^24.0"
ruff = "^0.5.0"
mypy = "^1.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"