[tool.poetry]
name = "db"
version = "0.1.0"
description = "SQLAlchemy models and database management for Minca AI Insurance Platform"
authors = ["Minca AI Team <team@mincaai.com>"]
packages = [{ include = "app", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
SQLAlchemy = "^2.0.30"
psycopg = {extras=["binary"], version="^3.1.18"}
alembic = "^1.13.1"
pgvector = "^0.3.2"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
black = "^24.0"
ruff = "^0.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"